-- Add bounding box and frame dimensions to events
ALTER TABLE events ADD COLUMN IF NOT EXISTS bbox_x1     REAL DEFAULT 0.0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS bbox_y1     REAL DEFAULT 0.0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS bbox_x2     REAL DEFAULT 0.0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS bbox_y2     REAL DEFAULT 0.0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS frame_width  INT  DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS frame_height INT  DEFAULT 0;
